spring.application.name=ielts
security.jwt.secret=CHANGE_ME_TO_LONG_RANDOM_SECRET_64+_CHARS
security.jwt.ttlSeconds=86400
spring.jpa.properties.hibernate.default_schema=app
springdoc.swagger-ui.persistAuthorization=true
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true
server.error.include-stacktrace=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

