server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ielts_center
    username: farishta
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: app
    open-in-view: false

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_STRING_AT_LEAST_32_CHARS"
    issuer: "ielts-centre"

anthropic:
  api:
    key: ${ANTHROPIC_API_KEY:-}
    model: claude-3-5-haiku-20241022
